/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

export default {
  docs: [
    // TODO: fix sidebar item order
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  mods: [
    {
      type: "autogenerated",
      dirName: "mods",
    },
  ],
} satisfies SidebarsConfig;
